#include "src/observer/observer.h"
#include "src/graphics/window/window_observer.h"
#include "src/graphics/window/window.h"
#include "src/board/board.h"
#include "src/simulation/simulation.h"
#include "src/cell/cell.h"
//#include "src/utils/utils.h"